################################################
################################################
#Task 1
library("matrixStats")

ap = matrix(AirPassengers, ncol = 12, byrow = TRUE, dimnames = list(as.character(1949:1960), month.abb))
indices = which(ap == max(ap), arr.ind = TRUE)
sprintf("The max revenue is from %d people in %s %s.", max(AirPassengers), colnames(ap)[indices[2]], rownames(ap)[indices[1]])

total_passengers <- rowSums(ap)
ind = which(total_passengers == max(total_passengers), arr.ind = TRUE)
sprintf("The max revenue generated was in %s", names(total_passengers)[ind[1]])


plot(total_passengers, ylab = "Passengers", xlab= "Years", type = "o", pch=20)
#################################################
#################################################
#Task 2

ticket_prices <- 8000
for (i in 2:12)
{
  ticket_prices[i] <- ticket_prices[i-1]*1.1
}

monthly_revenues <- matrix(ncol=12, nrow=12, dimnames = list(as.character(1949:1960), month.abb))

monthly_revenues<-ap*ticket_prices

indi = which(monthly_revenues == max(monthly_revenues), arr.ind = TRUE)
sprintf("The max revenue generated in one month was Rs. %f in %s %s.", max(monthly_revenues), colnames(monthly_revenues)[indi[2]], rownames(monthly_revenues)[indi[1]])

yearly_revenues <- rowSums(monthly_revenues)
indices = which(yearly_revenues = max(yearly_revenues), arr.ind = TRUE)
sprintf("The max revenue generated was Rs. %f in %s", max(yearly_revenues), names(yearly_revenues)[indices[1]])

total_revenue <- sum(yearly_revenues)
sprintf("The total revenue generated by the company between 1949 and 1960 is: Rs. %f",total_revenue)

#################################################
#################################################
#Task 3

trending_months<-colSums(ap)

plot(trending_months, ylab = "Passengers", xlab= "Months", type = "o", pch=20)


